import 'package:intl/intl.dart';
import 'package:pdf/pdf.dart';
import 'package:pdf/widgets.dart' as pw;

import '../data/daos.dart';
import '../data/db.dart';

/// Built-in PDF fonts lack the ₹ glyph, so the report uses "Rs".
final _rsFmt = NumberFormat.currency(locale: 'en_IN', symbol: 'Rs ');

String formatPaise(int paise) => _rsFmt.format(paise / 100);

/// Monthly statement: totals, per-category breakdown, budget status.
class PdfReport {
  final AppDb db;

  PdfReport(this.db);

  Future<List<int>> build(DateTime month) async {
    final txns = await db.monthTransactions(month);
    final cats = {for (final c in await db.allCategories()) c.id: c};
    final byCat = await db.spendByCategory(month);
    final budgets = await (db.select(db.budgets)
          ..where((b) => b.active.equals(true)))
        .get();

    final spent = byCat.values.fold(0, (a, b) => a + b);
    final received = txns
        .where((t) => t.direction == TxnDirection.credit)
        .fold(0, (a, t) => a + t.amountPaise);
    final catRows = byCat.entries.toList()
      ..sort((a, b) => b.value.compareTo(a.value));

    final doc = pw.Document();
    final title = DateFormat('MMMM yyyy').format(month);
    doc.addPage(pw.MultiPage(
      build: (context) => [
        pw.Header(
            level: 0,
            child: pw.Text('FinTrack · $title',
                style: pw.TextStyle(
                    fontSize: 22, fontWeight: pw.FontWeight.bold))),
        pw.SizedBox(height: 8),
        pw.Row(children: [
          _stat('Spent', formatPaise(spent)),
          pw.SizedBox(width: 24),
          _stat('Received', formatPaise(received)),
          pw.SizedBox(width: 24),
          _stat('Transactions', '${txns.length}'),
        ]),
        pw.SizedBox(height: 20),
        pw.Text('By category',
            style:
                pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
        pw.SizedBox(height: 8),
        pw.TableHelper.fromTextArray(
          headers: ['Category', 'Amount', 'Share'],
          data: [
            for (final e in catRows)
              [
                e.key == null ? 'Uncategorized' : cats[e.key]!.name,
                formatPaise(e.value),
                spent == 0 ? '-' : '${(e.value * 100 / spent).round()}%',
              ],
          ],
          headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          cellAlignments: {
            1: pw.Alignment.centerRight,
            2: pw.Alignment.centerRight
          },
        ),
        if (budgets.isNotEmpty) ...[
          pw.SizedBox(height: 20),
          pw.Text('Budgets',
              style:
                  pw.TextStyle(fontSize: 14, fontWeight: pw.FontWeight.bold)),
          pw.SizedBox(height: 8),
          pw.TableHelper.fromTextArray(
            headers: ['Scope', 'Limit', 'Spent', 'Status'],
            data: [
              for (final b in budgets)
                _budgetRow(b, cats, byCat, spent),
            ],
            headerStyle: pw.TextStyle(fontWeight: pw.FontWeight.bold),
          ),
        ],
        pw.SizedBox(height: 24),
        pw.Text(
            'Generated by FinTrack · all data stays on your device',
            style:
                const pw.TextStyle(fontSize: 9, color: PdfColors.grey600)),
      ],
    ));
    return doc.save();
  }

  static List<String> _budgetRow(Budget b, Map<int, Category> cats,
      Map<int?, int> byCat, int totalSpent) {
    final scope = b.categoryId == null ? 'Overall' : cats[b.categoryId]!.name;
    final used = b.categoryId == null ? totalSpent : (byCat[b.categoryId] ?? 0);
    final over = used > b.amountPaise;
    return [
      scope,
      formatPaise(b.amountPaise),
      formatPaise(used),
      over ? 'OVER by ${formatPaise(used - b.amountPaise)}' : 'Within limit',
    ];
  }

  static pw.Widget _stat(String label, String value) => pw.Column(
        crossAxisAlignment: pw.CrossAxisAlignment.start,
        children: [
          pw.Text(label,
              style:
                  const pw.TextStyle(fontSize: 10, color: PdfColors.grey600)),
          pw.Text(value,
              style: pw.TextStyle(
                  fontSize: 16, fontWeight: pw.FontWeight.bold)),
        ],
      );
}
